import React, { useEffect, useState } from "react";
import { HotdropABI } from "../../solidity/utils/Hotdrop";
import { useMoralis, useWeb3ExecuteFunction } from "react-moralis";
import { toast } from "react-toastify";
import Web3 from "web3";
import { AbiItem } from "web3-utils";
import { atom, useAtom } from "jotai";
import { Modal } from "../Modal";
import { GenericSubmission } from "../../types";
import { Web3_Socket_URL } from "../../utils/constants";

// TODO: set toast messages for onsuccess and error
// TODO: add price to constants file currently on main (work on that was done after starting this branch)

const mintingModalOpenAtom = atom<boolean>(false);
export const useMintingModalOpen = () => useAtom(mintingModalOpenAtom);

const mintingModalSubmissionAtom = atom<GenericSubmission>({
  submissionID: 'not set', // UUID Required but generated by DB
  isArtist: false,
  hotdropAddress: 'not set',
  mediaURI: 'not set',
  submitterWallet: 'not set',
  mediaTitle: 'not set',
});
export const useMintingModalSubmission = () => useAtom(mintingModalSubmissionAtom);

export const MintingModal = () => {
  const [submissionAtom, setSubmissionAtom] = useMintingModalSubmission();
  const [showModal, setShowModal] = useMintingModalOpen();
  const [totalMints, setTotalMints] = useState(0)
  const { isWeb3Enabled, account } = useMoralis();
  const { fetch: runContractFunction, data, error, isLoading, isFetching, } = useWeb3ExecuteFunction();

  // isLoading: user action required - (metamask popup open)
  const [loading, setLoading] = useState<boolean | string>(false);

  const web3 = new Web3(Web3_Socket_URL);

  useEffect(() => {
    async function fetchContractData() {
      const data = await loadContractData();
    }
    if (submissionAtom.hotdropAddress !== 'not set'){

      fetchContractData();
    }
  }, [submissionAtom]);

  useEffect(() => {
    if (isLoading) setLoading('User action required');
  }, [isLoading]);

  const loadContractData = async () => {
    const hotdropContract = new web3.eth.Contract(HotdropABI as unknown as AbiItem, submissionAtom.hotdropAddress);
    const contractInfo = await hotdropContract.methods.totalSupply(3).call()
    setTotalMints(contractInfo)
  }

  const closeModal = () => {
    setShowModal(false);
  };

  const options = {
    abi: HotdropABI,
    contractAddress: submissionAtom.hotdropAddress,
    functionName: "saleMint",
    params: {
      amount: 1,
    },
    msgValue: '10000000000000000'
  }

  const mintNFT = async () => {
    if (!isWeb3Enabled) {
      throw "Authentication failed";
    }

    setLoading("Loading Transaction");

    const submitTransaction = await runContractFunction({
      params: options,
      onError: (err) => {
        console.log(err)
      },
      onSuccess: (res) => {
        console.log(res);
      },
    });

    // @ts-ignore
    const contractResult = await submitTransaction.wait();

    console.log('contract result', contractResult);

    setLoading(false);


  }

  return (
    <Modal open={showModal} onClose={closeModal} width="40rem" height="27rem">
      <div className="justify-center items-center flex fixed inset-0 z-50 outline-none focus:outline-none">
        <div className="text-white relative min-w-fit	 my-6 mx-auto max-w-6xl p-80">
          {/*content*/}

          <div className="fixed inset-0 transition-opacity">
            <div className="absolute inset-0 bg-gray-900 opacity-75"></div>
          </div>

          <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full">
            {/*header*/}
            <div className="flex justify-end p-5 border-b border-solid border-slate-200 rounded-t">
              <button
                className="text-white background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                type="button"
                onClick={closeModal}
              >
                Close
              </button>
            </div>

            {/*body*/}
            <div className="relative p-6 flex-auto text-white justify-center overflow-hidden pr-20">
              <div className="text-white uppercase text-2xl font-bold mb-4">
                {submissionAtom.artistName} - {submissionAtom.mediaTitle}
              </div>
              <div className="flex mb-4">
                <div className="w-1/3 text-gray-300 text-md font-semibold mr-2">Submitter Wallet:</div>
                <div className="w-2/3 text-gray-300 text-base">{submissionAtom.submitterWallet}</div>
              </div>
              <div className="flex mb-4">
                <div className="w-1/3 text-gray-300 text-sm font-semibold mr-2">Song Contract Address:</div>
                <div className="w-2/3 text-gray-300 text-base">{submissionAtom.hotdropAddress}</div>
              </div>
              <div className="flex justify-end mt-6">
                <span className="text-xl underline">Units Sold So far: {totalMints} / 25</span>
              </div>

            </div>
            {/*footer*/}
            <div className="flex items-center justify-between p-6 rounded-b">
              {submissionAtom.hotdropAddress == "" ? (
                <button
                  className="w-full text-black px-6 py-3 bg-gray-300 rounded focus:outline-none cursor-not-allowed	"
                  type="button">
                  This contract does not exist
                </button>
              ) : (
                <button
                  className="bg-white w-full text-black active:bg-gray-400 font-bold uppercase text-sm px-6 py-3 rounded-full shadow hover:bg-gray-400 outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                  type="button"
                  onClick={mintNFT}
                >
                  {isLoading? "Loading Transaction..." : "Mint"}
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
      <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
    </Modal>
  );
};
